// <auto-generated />
using System;
using System.Collections.Generic;
using API.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace API.Database.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260129141025_ClasstimeShortTimesNullable")]
    partial class ClasstimeShortTimesNullable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "pg_trgm");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("API.Database.Entities.Achievements.Achievement", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CreatorId")
                        .HasColumnType("integer");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<int>("ScaleId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CreatorId");

                    b.HasIndex("Date");

                    b.HasIndex("ScaleId");

                    b.HasIndex("Date", "Id");

                    b.ToTable("Achievements");
                });

            modelBuilder.Entity("API.Database.Entities.Achievements.AchievementScale", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.HasKey("Id");

                    b.ToTable("AchievementScales");
                });

            modelBuilder.Entity("API.Database.Entities.Achievements.AchievementStudent", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AchievementId")
                        .HasColumnType("integer");

                    b.Property<int>("AchievementTypeId")
                        .HasColumnType("integer");

                    b.Property<int>("ClassroomId")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("AchievementId");

                    b.HasIndex("AchievementTypeId");

                    b.HasIndex("ClassroomId");

                    b.ToTable("AchievementStudents");
                });

            modelBuilder.Entity("API.Database.Entities.Achievements.AchievementType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.HasKey("Id");

                    b.ToTable("AchievementTypes");
                });

            modelBuilder.Entity("API.Database.Entities.Appointments.Appointment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("AppointmentDateId")
                        .HasColumnType("integer");

                    b.Property<string>("AttendeeEmail")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("AttendeeName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<int>("HostId")
                        .HasColumnType("integer");

                    b.Property<string>("Link")
                        .HasColumnType("text");

                    b.Property<string>("Note")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("AppointmentDateId");

                    b.HasIndex("AttendeeEmail");

                    b.HasIndex("HostId");

                    b.HasIndex("AttendeeEmail", "AppointmentDateId")
                        .IsUnique()
                        .HasDatabaseName("IX_UniqueAttendeeDate");

                    b.HasIndex("HostId", "AppointmentDateId")
                        .IsUnique()
                        .HasDatabaseName("IX_UniqueHostDate");

                    b.HasIndex("HostId", "AttendeeEmail")
                        .IsUnique()
                        .HasDatabaseName("IX_UniqueHost");

                    b.ToTable("Appointments");
                });

            modelBuilder.Entity("API.Database.Entities.Appointments.AppointmentDate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("TypeId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Date");

                    b.HasIndex("TypeId", "Date");

                    b.ToTable("AppointmentDates");
                });

            modelBuilder.Entity("API.Database.Entities.Appointments.AppointmentReservedDate", b =>
                {
                    b.Property<int>("DateId")
                        .HasColumnType("integer");

                    b.Property<int>("HostId")
                        .HasColumnType("integer");

                    b.HasKey("DateId", "HostId");

                    b.HasIndex("HostId");

                    b.ToTable("AppointmentReservedDates");
                });

            modelBuilder.Entity("API.Database.Entities.Appointments.AppointmentType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<int>("DurationInMinutes")
                        .HasColumnType("integer");

                    b.Property<bool>("IsOnline")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsPublic")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<DateTime>("RegistrationEndsAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("AppointmentTypes");
                });

            modelBuilder.Entity("API.Database.Entities.Authorization.AppUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<bool>("IsSuspended")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsTeacher")
                        .HasColumnType("boolean");

                    b.Property<string>("JobTitle")
                        .HasColumnType("text");

                    b.Property<string>("Location")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedName")
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("text")
                        .HasComputedColumnSql("translate(upper(\"Name\"), 'ĄČĘĖĮŠŲŪŽ', 'ACEEISUUZ')", true);

                    b.PrimitiveCollection<List<string>>("Roles")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("Name");

                    b.HasIndex("NormalizedName");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("NormalizedName"), "GIN");
                    NpgsqlIndexBuilderExtensions.HasOperators(b.HasIndex("NormalizedName"), new[] { "gin_trgm_ops" });

                    b.HasIndex("UserName")
                        .IsUnique();

                    b.HasIndex("IsTeacher", "IsSuspended", "Name");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("API.Database.Entities.Authorization.RefreshToken", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<byte[]>("TokenHash")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("bytea");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("TokenHash")
                        .IsUnique();

                    b.HasIndex("UserId");

                    b.HasIndex("TokenHash", "ExpiresAt");

                    b.ToTable("RefreshTokens");
                });

            modelBuilder.Entity("API.Database.Entities.BullyReports.BullyReport", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Actions")
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)");

                    b.Property<string>("BullyName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("CreatorId")
                        .HasColumnType("integer");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date");

                    b.Property<string>("Details")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)");

                    b.Property<bool>("IsPublicReport")
                        .HasColumnType("boolean");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("Observers")
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)");

                    b.Property<string>("VictimName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("CreatorId");

                    b.HasIndex("CreatorId", "CreatedAt");

                    b.ToTable("BullyReports");
                });

            modelBuilder.Entity("API.Database.Entities.CMS.Banner", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Height")
                        .HasColumnType("integer");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<bool>("IsPublished")
                        .HasColumnType("boolean");

                    b.Property<string>("LanguageId")
                        .IsRequired()
                        .HasColumnType("character varying(5)");

                    b.Property<string>("NormalizedTitle")
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("text")
                        .HasComputedColumnSql("translate(upper(\"Title\"), 'ĄČĘĖĮŠŲŪŽ', 'ACEEISUUZ')", true);

                    b.Property<int>("Order")
                        .HasColumnType("integer");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<int>("Width")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedTitle");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("NormalizedTitle"), "GIN");
                    NpgsqlIndexBuilderExtensions.HasOperators(b.HasIndex("NormalizedTitle"), new[] { "gin_trgm_ops" });

                    b.HasIndex("LanguageId", "IsPublished", "Order", "Id");

                    b.ToTable("Banners");
                });

            modelBuilder.Entity("API.Database.Entities.CMS.Language", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(5)
                        .HasColumnType("character varying(5)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.HasKey("Id");

                    b.ToTable("Languages");
                });

            modelBuilder.Entity("API.Database.Entities.CMS.Menu", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsExternal")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsHidden")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsPublished")
                        .HasColumnType("boolean");

                    b.Property<string>("LanguageId")
                        .IsRequired()
                        .HasColumnType("character varying(5)");

                    b.Property<string>("NormalizedTitle")
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("text")
                        .HasComputedColumnSql("translate(upper(\"Title\"), 'ĄČĘĖĮŠŲŪŽ', 'ACEEISUUZ')", true);

                    b.Property<int>("Order")
                        .HasColumnType("integer");

                    b.Property<int?>("ParentMenuId")
                        .HasColumnType("integer");

                    b.Property<int?>("PostId")
                        .HasColumnType("integer");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("Url")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("LanguageId");

                    b.HasIndex("NormalizedTitle");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("NormalizedTitle"), "GIN");
                    NpgsqlIndexBuilderExtensions.HasOperators(b.HasIndex("NormalizedTitle"), new[] { "gin_trgm_ops" });

                    b.HasIndex("Order");

                    b.HasIndex("ParentMenuId");

                    b.HasIndex("PostId")
                        .IsUnique();

                    b.HasIndex("LanguageId", "Url", "IsPublished");

                    b.HasIndex("LanguageId", "IsPublished", "IsHidden", "Order", "Id");

                    b.ToTable("Menus");
                });

            modelBuilder.Entity("API.Database.Entities.CMS.Post", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("FeaturedImage")
                        .HasColumnType("text");

                    b.PrimitiveCollection<List<string>>("Files")
                        .HasColumnType("text[]");

                    b.PrimitiveCollection<List<string>>("Images")
                        .HasColumnType("text[]");

                    b.Property<string>("IntroText")
                        .HasColumnType("text");

                    b.Property<bool>("IsFeatured")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsPublished")
                        .HasColumnType("boolean");

                    b.Property<string>("LanguageId")
                        .IsRequired()
                        .HasColumnType("character varying(5)");

                    b.Property<string>("Meta")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NormalizedTitle")
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("text")
                        .HasComputedColumnSql("translate(upper(\"Title\"), 'ĄČĘĖĮŠŲŪŽ', 'ACEEISUUZ')", true);

                    b.Property<DateTime>("PublishedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("ShowInFeed")
                        .HasColumnType("boolean");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("Text")
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedTitle");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("NormalizedTitle"), "GIN");
                    NpgsqlIndexBuilderExtensions.HasOperators(b.HasIndex("NormalizedTitle"), new[] { "gin_trgm_ops" });

                    b.HasIndex("IsFeatured", "PublishedAt");

                    b.HasIndex("LanguageId", "IsPublished", "ShowInFeed", "IsFeatured", "PublishedAt");

                    b.ToTable("Posts");
                });

            modelBuilder.Entity("API.Database.Entities.Courses.Course", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Certificate")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<int>("CreatorId")
                        .HasColumnType("integer");

                    b.Property<double>("DurationInHours")
                        .HasColumnType("double precision");

                    b.Property<DateOnly>("EndDate")
                        .HasColumnType("date");

                    b.Property<bool>("IsUseful")
                        .HasColumnType("boolean");

                    b.Property<string>("Organizer")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("date");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("CreatorId");

                    b.HasIndex("EndDate");

                    b.HasIndex("StartDate");

                    b.HasIndex("StartDate", "Id");

                    b.ToTable("Courses");
                });

            modelBuilder.Entity("API.Database.Entities.FailureReports.FailureReport", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CreatorId")
                        .HasColumnType("integer");

                    b.Property<string>("Details")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<DateTime?>("FixDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool?>("IsFixed")
                        .HasColumnType("boolean");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTime>("ReportDate")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("CreatorId");

                    b.HasIndex("ReportDate");

                    b.HasIndex("IsFixed", "Id");

                    b.ToTable("FailureReports");
                });

            modelBuilder.Entity("API.Database.Entities.Observations.Observation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CreatorId")
                        .HasColumnType("integer");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date");

                    b.Property<int>("LessonId")
                        .HasColumnType("integer");

                    b.Property<string>("Note")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<int>("StudentId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CreatorId");

                    b.HasIndex("LessonId");

                    b.HasIndex("StudentId");

                    b.HasIndex("CreatorId", "Id");

                    b.HasIndex("Date", "Id");

                    b.HasIndex("StudentId", "Date", "Id");

                    b.ToTable("Observations");
                });

            modelBuilder.Entity("API.Database.Entities.Observations.ObservationLesson", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("ObservationLessons");
                });

            modelBuilder.Entity("API.Database.Entities.Observations.ObservationOption", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("ObservationOptions");
                });

            modelBuilder.Entity("API.Database.Entities.Observations.ObservationStudent", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("ObservationStudents");
                });

            modelBuilder.Entity("API.Database.Entities.School.Classday", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.HasKey("Id");

                    b.ToTable("Classdays");
                });

            modelBuilder.Entity("API.Database.Entities.School.Classroom", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.HasKey("Id");

                    b.ToTable("Classrooms");
                });

            modelBuilder.Entity("API.Database.Entities.School.Classtime", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer");

                    b.Property<TimeOnly>("EndTime")
                        .HasColumnType("time without time zone");

                    b.Property<TimeOnly?>("EndTimeShort")
                        .HasColumnType("time without time zone");

                    b.Property<TimeOnly>("StartTime")
                        .HasColumnType("time without time zone");

                    b.Property<TimeOnly?>("StartTimeShort")
                        .HasColumnType("time without time zone");

                    b.HasKey("Id");

                    b.ToTable("Classtimes");
                });

            modelBuilder.Entity("API.Database.Entities.School.ShortDay", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date");

                    b.HasKey("Id");

                    b.HasIndex("Date")
                        .IsUnique();

                    b.ToTable("ShortDays");
                });

            modelBuilder.Entity("API.Database.Entities.School.Timetable", b =>
                {
                    b.Property<int>("DayId")
                        .HasColumnType("integer");

                    b.Property<int>("TimeId")
                        .HasColumnType("integer");

                    b.Property<int>("RoomId")
                        .HasColumnType("integer");

                    b.Property<string>("ClassName")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.HasKey("DayId", "TimeId", "RoomId");

                    b.HasIndex("TimeId");

                    b.HasIndex("RoomId", "DayId");

                    b.ToTable("Timetable");
                });

            modelBuilder.Entity("API.Database.Entities.School.TimetableOverride", b =>
                {
                    b.Property<DateOnly>("Date")
                        .HasColumnType("date");

                    b.Property<int>("TimeId")
                        .HasColumnType("integer");

                    b.Property<int>("RoomId")
                        .HasColumnType("integer");

                    b.Property<string>("ClassName")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.HasKey("Date", "TimeId", "RoomId");

                    b.HasIndex("RoomId");

                    b.HasIndex("TimeId");

                    b.HasIndex("Date", "RoomId");

                    b.ToTable("TimetableOverrides");
                });

            modelBuilder.Entity("API.Database.Entities.Settings.Settings", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("Data")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.HasKey("Id");

                    b.ToTable("Settings");
                });

            modelBuilder.Entity("API.Services.JobQueue.JobRecord", b =>
                {
                    b.Property<Guid>("TrackingID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Command")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<DateTime>("ExecuteAfter")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("ExpireOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsComplete")
                        .HasColumnType("boolean");

                    b.Property<string>("QueueID")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("TrackingID");

                    b.ToTable("JobRecord");
                });

            modelBuilder.Entity("AchievementAppUser", b =>
                {
                    b.Property<int>("AchievementId")
                        .HasColumnType("integer");

                    b.Property<int>("AdditionalTeachersId")
                        .HasColumnType("integer");

                    b.HasKey("AchievementId", "AdditionalTeachersId");

                    b.HasIndex("AdditionalTeachersId");

                    b.ToTable("AchievementAppUser");
                });

            modelBuilder.Entity("AppUserAppointmentType", b =>
                {
                    b.Property<int>("AdditionalInviteesId")
                        .HasColumnType("integer");

                    b.Property<int>("AppointmentTypeId")
                        .HasColumnType("integer");

                    b.HasKey("AdditionalInviteesId", "AppointmentTypeId");

                    b.HasIndex("AppointmentTypeId");

                    b.ToTable("AppUserAppointmentType");
                });

            modelBuilder.Entity("AppUserAppointmentType1", b =>
                {
                    b.Property<int>("AppointmentType1Id")
                        .HasColumnType("integer");

                    b.Property<int>("ExclusiveHostsId")
                        .HasColumnType("integer");

                    b.HasKey("AppointmentType1Id", "ExclusiveHostsId");

                    b.HasIndex("ExclusiveHostsId");

                    b.ToTable("AppUserAppointmentType1");
                });

            modelBuilder.Entity("ObservationObservationOption", b =>
                {
                    b.Property<int>("ObservationsId")
                        .HasColumnType("integer");

                    b.Property<int>("OptionsId")
                        .HasColumnType("integer");

                    b.HasKey("ObservationsId", "OptionsId");

                    b.HasIndex("OptionsId");

                    b.ToTable("ObservationObservationOption");
                });

            modelBuilder.Entity("API.Database.Entities.Achievements.Achievement", b =>
                {
                    b.HasOne("API.Database.Entities.Authorization.AppUser", "Creator")
                        .WithMany()
                        .HasForeignKey("CreatorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("API.Database.Entities.Achievements.AchievementScale", "Scale")
                        .WithMany()
                        .HasForeignKey("ScaleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Creator");

                    b.Navigation("Scale");
                });

            modelBuilder.Entity("API.Database.Entities.Achievements.AchievementStudent", b =>
                {
                    b.HasOne("API.Database.Entities.Achievements.Achievement", "Achievement")
                        .WithMany("Students")
                        .HasForeignKey("AchievementId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("API.Database.Entities.Achievements.AchievementType", "AchievementType")
                        .WithMany()
                        .HasForeignKey("AchievementTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("API.Database.Entities.School.Classroom", "Classroom")
                        .WithMany()
                        .HasForeignKey("ClassroomId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Achievement");

                    b.Navigation("AchievementType");

                    b.Navigation("Classroom");
                });

            modelBuilder.Entity("API.Database.Entities.Appointments.Appointment", b =>
                {
                    b.HasOne("API.Database.Entities.Appointments.AppointmentDate", "AppointmentDate")
                        .WithMany()
                        .HasForeignKey("AppointmentDateId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("API.Database.Entities.Authorization.AppUser", "Host")
                        .WithMany()
                        .HasForeignKey("HostId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AppointmentDate");

                    b.Navigation("Host");
                });

            modelBuilder.Entity("API.Database.Entities.Appointments.AppointmentDate", b =>
                {
                    b.HasOne("API.Database.Entities.Appointments.AppointmentType", "Type")
                        .WithMany()
                        .HasForeignKey("TypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Type");
                });

            modelBuilder.Entity("API.Database.Entities.Appointments.AppointmentReservedDate", b =>
                {
                    b.HasOne("API.Database.Entities.Appointments.AppointmentDate", null)
                        .WithMany()
                        .HasForeignKey("DateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("API.Database.Entities.Authorization.AppUser", null)
                        .WithMany()
                        .HasForeignKey("HostId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("API.Database.Entities.Authorization.RefreshToken", b =>
                {
                    b.HasOne("API.Database.Entities.Authorization.AppUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("API.Database.Entities.BullyReports.BullyReport", b =>
                {
                    b.HasOne("API.Database.Entities.Authorization.AppUser", "Creator")
                        .WithMany()
                        .HasForeignKey("CreatorId");

                    b.Navigation("Creator");
                });

            modelBuilder.Entity("API.Database.Entities.CMS.Banner", b =>
                {
                    b.HasOne("API.Database.Entities.CMS.Language", "Language")
                        .WithMany()
                        .HasForeignKey("LanguageId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Language");
                });

            modelBuilder.Entity("API.Database.Entities.CMS.Menu", b =>
                {
                    b.HasOne("API.Database.Entities.CMS.Language", "Language")
                        .WithMany()
                        .HasForeignKey("LanguageId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("API.Database.Entities.CMS.Menu", "ParentMenu")
                        .WithMany()
                        .HasForeignKey("ParentMenuId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("API.Database.Entities.CMS.Post", "Post")
                        .WithOne()
                        .HasForeignKey("API.Database.Entities.CMS.Menu", "PostId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Language");

                    b.Navigation("ParentMenu");

                    b.Navigation("Post");
                });

            modelBuilder.Entity("API.Database.Entities.CMS.Post", b =>
                {
                    b.HasOne("API.Database.Entities.CMS.Language", "Language")
                        .WithMany()
                        .HasForeignKey("LanguageId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Language");
                });

            modelBuilder.Entity("API.Database.Entities.Courses.Course", b =>
                {
                    b.HasOne("API.Database.Entities.Authorization.AppUser", "Creator")
                        .WithMany()
                        .HasForeignKey("CreatorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Creator");
                });

            modelBuilder.Entity("API.Database.Entities.FailureReports.FailureReport", b =>
                {
                    b.HasOne("API.Database.Entities.Authorization.AppUser", "Creator")
                        .WithMany()
                        .HasForeignKey("CreatorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Creator");
                });

            modelBuilder.Entity("API.Database.Entities.Observations.Observation", b =>
                {
                    b.HasOne("API.Database.Entities.Authorization.AppUser", "Creator")
                        .WithMany()
                        .HasForeignKey("CreatorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("API.Database.Entities.Observations.ObservationLesson", "Lesson")
                        .WithMany()
                        .HasForeignKey("LessonId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("API.Database.Entities.Observations.ObservationStudent", "Student")
                        .WithMany()
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Creator");

                    b.Navigation("Lesson");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("API.Database.Entities.School.Timetable", b =>
                {
                    b.HasOne("API.Database.Entities.School.Classday", "Day")
                        .WithMany()
                        .HasForeignKey("DayId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("API.Database.Entities.School.Classroom", "Room")
                        .WithMany()
                        .HasForeignKey("RoomId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("API.Database.Entities.School.Classtime", "Time")
                        .WithMany()
                        .HasForeignKey("TimeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Day");

                    b.Navigation("Room");

                    b.Navigation("Time");
                });

            modelBuilder.Entity("API.Database.Entities.School.TimetableOverride", b =>
                {
                    b.HasOne("API.Database.Entities.School.Classroom", "Room")
                        .WithMany()
                        .HasForeignKey("RoomId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("API.Database.Entities.School.Classtime", "Time")
                        .WithMany()
                        .HasForeignKey("TimeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Room");

                    b.Navigation("Time");
                });

            modelBuilder.Entity("AchievementAppUser", b =>
                {
                    b.HasOne("API.Database.Entities.Achievements.Achievement", null)
                        .WithMany()
                        .HasForeignKey("AchievementId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("API.Database.Entities.Authorization.AppUser", null)
                        .WithMany()
                        .HasForeignKey("AdditionalTeachersId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("AppUserAppointmentType", b =>
                {
                    b.HasOne("API.Database.Entities.Authorization.AppUser", null)
                        .WithMany()
                        .HasForeignKey("AdditionalInviteesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("API.Database.Entities.Appointments.AppointmentType", null)
                        .WithMany()
                        .HasForeignKey("AppointmentTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("AppUserAppointmentType1", b =>
                {
                    b.HasOne("API.Database.Entities.Appointments.AppointmentType", null)
                        .WithMany()
                        .HasForeignKey("AppointmentType1Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("API.Database.Entities.Authorization.AppUser", null)
                        .WithMany()
                        .HasForeignKey("ExclusiveHostsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ObservationObservationOption", b =>
                {
                    b.HasOne("API.Database.Entities.Observations.Observation", null)
                        .WithMany()
                        .HasForeignKey("ObservationsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("API.Database.Entities.Observations.ObservationOption", null)
                        .WithMany()
                        .HasForeignKey("OptionsId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("API.Database.Entities.Achievements.Achievement", b =>
                {
                    b.Navigation("Students");
                });
#pragma warning restore 612, 618
        }
    }
}
